fix

diff --git a/.github/workflows/nightly-deployment.yml b/.github/workflows/nightly-deployment.yml
--- a/.github/workflows/nightly-deployment.yml
+++ b/.github/workflows/nightly-deployment.yml
@@ -92,15 +92,15 @@ jobs:
 
             echo "🚀 Setup Complete!"
 
-      - name: Free up port 3306 before starting MySQL
+      - name: Free up port 3307 before starting MySQL
         run: |
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/bookshop-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
             echo "🔍 Checking for processes using port 3306..."
-            if sudo lsof -i :3306; then
-              echo "⚠️ Port 3306 is in use, stopping process..."
-              sudo fuser -k 3306/tcp || echo "Failed to kill process"
+            if sudo lsof -i :3307; then
+              echo "⚠️ Port 3307 is in use, stopping process..."
+              sudo fuser -k 3307/tcp || echo "Failed to kill process"
             else
-              echo "✅ Port 3306 is free"
+              echo "✅ Port 3307 is free"
             fi
           EOF
 
@@ -119,22 +119,25 @@ jobs:
 
             echo "🔍 Checking if backend is running..."
             curl -sSf http://localhost:8800/books || (echo "❌ Backend not responding!" && exit 1)
+            echo "🔍 Checking if frontend is running..."
+            curl -Isf http://localhost:3000 || (echo "❌ frontend not responding!" && exit 1)
+
 
             echo "✅ Smoke Test Passed!"
           EOF
       
-      - name: Stop and Remove All Docker Containers
-        run: |
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/bookshop-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
-            echo "🛑 Stopping all running containers..."
-            docker stop $(docker ps -aq) || echo "No running containers"
-            docker rm $(docker ps -aq) || echo "No containers to remove"
+      # - name: Stop and Remove All Docker Containers
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/bookshop-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
+      #       echo "🛑 Stopping all running containers..."
+      #       docker stop $(docker ps -aq) || echo "No running containers"
+      #       docker rm $(docker ps -aq) || echo "No containers to remove"
             
-            echo "🧹 Cleaning up Docker system..."
-            docker system prune -a -f
-            docker volume prune -f
-            docker network prune -f
-          EOF
+      #       echo "🧹 Cleaning up Docker system..."
+      #       docker system prune -a -f
+      #       docker volume prune -f
+      #       docker network prune -f
+      #     EOF
 
       # end EC2
       # - name: Terminate EC2 Instance
